pagopa/idpay-transactions

- helm/values-dev.yaml
- helm/values.yaml
Move environment independent configurations into values.yml
> Values yaml update

- src/main/resources/application.yml
* cosmosdb/mongodb idle timeout limit fixed
* cosmosdb/mongodb min pool sizes fixed
> Fix mongo idle timeout (#27)

- src/main/java/it/gov/pagopa/idpay/transactions/dto/RewardTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RewardTransaction.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/TransactionProcessed.java
- src/test/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapperTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionDTOFaker.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionFaker.java
* IREER-226 amountCents
* IREER-226 amountCents
> IREER-226 amountCents (#39)

- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
* IDP-1106 findById optimize to be run on cosmosDB
* extending coverage
> feat: IDP-1106 findById optimize to be run on cosmosDB (#74)

- src/main/java/it/gov/pagopa/idpay/transactions/service/commands/CommandsMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/commands/ops/DeleteInitiativeServiceImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify performance logs and info logs
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
> fix: info log for initiative delete

- .devops/deploy-pipelines.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
- Dockerfile
- helm/Chart.lock
- helm/Chart.yaml
- helm/values.yaml
- upgrade helmchart to 2.8.0
- update anchore action triggers (on push and workflow_dispatch)
- add proper .releaserc.json + bump to semantic-release v4
- add pull request template
- fix anchor skip steps
- helm timeout to 10m
> chore: [IDP-1693] Devops fixes

- .github/CODEOWNERS
- CODEOWNERS
> chore: update codeowners (#104)

- .github/workflows/anchore.yml
> chore: fix anchore skip step (#107)

- Dockerfile
> fix: IDP-1760 fix new critical CVE-2022-48174 (#110)

- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
> feat: IDP-1765 selected API retryable

- pom.xml
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
> feat: Release dev

- .grype.yaml
- Dockerfile
- pom.xml
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
- src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImplTest.java
> fix: Idp 2016 fix CVE

- .github/CODEOWNERS
- src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
- src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/BaseIntegrationTest.java
- src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
- src/test/resources/mongodbEmbeddedDisabled.properties
> chore: IDP-2102 configuring a single mongodb instance for all tests

- pom.xml
- src/main/java/it/gov/pagopa/idpay/transactions/dto/MerchantTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImpl.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImplTest.java
- Added field channel in MerchantTransactionDTO
- Map new field in MerchantTransactionServiceImpl
Recognize transaction's channel origin
> fix: [IDP-2014] add channel for transaction processed list 

- .github/CODEOWNERS
- Dockerfile
- pom.xml
- src/main/java/it/gov/pagopa/idpay/transactions/dto/MerchantTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImpl.java
- src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
- src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImplTest.java
- src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
- src/test/resources/mongodbEmbeddedDisabled.properties
- Configuring a single mongodb instance for all tests
- Added field channel in MerchantTransactionDTO
- Map new field in MerchantTransactionServiceImpl
> fix: promote to UAT

- helm/values.yaml
> fix: fix pdv base url config

- helm/values.yaml
> fix: fix pdv base url config (#135)

- pom.xml
- src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
- src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
- src/main/java/it/gov/pagopa/idpay/transactions/config/TransactionErrorManagerConfig.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/utils/ExceptionConstants.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImplTest.java
> feat: IDP-2074 new error codes

- pom.xml
- src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
- src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
- src/main/java/it/gov/pagopa/idpay/transactions/config/TransactionErrorManagerConfig.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/utils/ExceptionConstants.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/ErrorManagerTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImplTest.java
> feat: IDP-2074 new error codes (#138)

- .grype.yaml
- Dockerfile
- pom.xml
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- src/test/java/it/gov/pagopa/idpay/transactions/BaseIntegrationTest.java
> fix: IDP-2196 fix Cve

- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java
- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/main/java/it/gov/pagopa/idpay/transactions/config/KafkaConfiguration.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/TransactionErrorNotifierService.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/TransactionErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/commands/ops/DeleteInitiativeServiceImpl.java
- src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/config/KafkaConfigurationTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/TransactionErrorNotifierServiceImplTest.java
-Removed suppress warning
-Added configuration class
> fix: IDP-2365 fix bug e code smell sonar group

- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/TransactionsController.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/MerchantTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/RewardTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RefundInfo.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/Reward.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RewardTransaction.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/TransactionProcessed.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/counters/Counters.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/counters/RewardCounters.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepository.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/RewardTransactionService.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/RewardTransactionServiceImpl.java
- src/test/java/it/gov/pagopa/idpay/transactions/controller/TransactionsControllerImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapperTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/RewardTransactionServiceImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionDTOFaker.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionFaker.java
> fix: Idp 2467 fix management decimal amounts

- Dockerfile
- specs/asyncapi.yml
> chore: promotion to main - update runtime image

- .grype.yaml
- pom.xml
> chore: fix cve spring cloud

- .grype.yaml
- pom.xml
- Update spring cloud context to fix CVE
> chore: promote to UAT

- .grype.yaml
- Dockerfile
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/values.yaml
- pom.xml
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
> chore: fix cve spring

- .grype.yaml
- Dockerfile
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/values.yaml
- pom.xml
- specs/asyncapi.yml
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- Fix CVE [PR](https://github.com/pagopa/idpay-transactions/pull/165)
> chore: promote to MAIN

- .github/CODEOWNERS
- Dockerfile
- helm/values-dev.yaml
- pom.xml
> fix: cve (#172)

- helm/values-prod.yaml
- helm/values-uat.yaml
> chore: helm java_tool_options update

- src/main/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionController.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionControllerImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/PointOfSaleTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/PointOfSaleTransactionsListDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/RewardTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/PointOfSaleTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RewardTransaction.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepository.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionService.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/utils/Utilities.java
- src/test/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionControllerImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/dto/mapper/PointOfSaleTransactionMapperTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/MerchantTransactionServiceImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionServiceImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/PointOfSaleTransactionDTOFaker.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionDTOFaker.java
- src/test/java/it/gov/pagopa/idpay/transactions/test/fakers/RewardTransactionFaker.java
Added new endpoint to fetch processed transactions associated to a point of sale.
Introduction of the pointOfSaleId field in the model RewardTransaction.
Implemented new API to retrieve processed transactions associated to a point of sale.
Implemented unit tests related to the new feature.
> feat: [EBE-118] API to retrieve processed transactions

- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/utils/AggregationConstants.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
Added logical sorting for processed transactions status.
Introduced aggregation to enforce status ordering.
> feat: [EBE-185] Add logical sorting for transaction status

- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
Handle custom field mapping for pageable sort.
Updated RewardTransactionSpecificRepositoryImpl to map updateDate sort to elaborationDateTime.
Added unit tests.
> fix: handle custom field mapping for pageable sort

- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/utils/AggregationConstants.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
Updated product sorting.
Removed product category aggregation, now sorting uses additionalProperties.productName directly.
Updated unit tests.
> fix: updated product sorting

- src/main/java/it/gov/pagopa/idpay/transactions/dto/InvoiceFile.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/PointOfSaleTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/RewardTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/PointOfSaleTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RewardTransaction.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/TransactionProcessed.java
- src/test/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapperTest.java
> feat: [EBE-258] adding invoice file

- src/main/java/it/gov/pagopa/idpay/transactions/dto/InvoiceFile.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/PointOfSaleTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/RewardTransactionDTO.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/PointOfSaleTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapper.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/RewardTransaction.java
- src/main/java/it/gov/pagopa/idpay/transactions/model/TransactionProcessed.java
- src/test/java/it/gov/pagopa/idpay/transactions/dto/mapper/RewardTransactionMapperTest.java
> feat: promote to UAT

- src/main/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionController.java
- src/main/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionControllerImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepository.java
- src/main/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionService.java
- src/main/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionServiceImpl.java
- src/main/java/it/gov/pagopa/idpay/transactions/storage/BlobStorageClientConfig.java
- src/main/java/it/gov/pagopa/idpay/transactions/storage/BlobStorageProperties.java
- src/main/java/it/gov/pagopa/idpay/transactions/storage/InvoiceStorageClient.java
- src/test/java/it/gov/pagopa/idpay/transactions/controller/PointOfSaleTransactionControllerImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/repository/RewardTransactionSpecificRepositoryTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/service/PointOfSaleTransactionServiceImplTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/storage/BlobStorageClientConfigTest.java
- src/test/java/it/gov/pagopa/idpay/transactions/storage/InvoiceStorageClientTest.java
Updated download api.
Removed x-initiative-id header parameter from download api.
Replaced Autowired and Value constructor injections with ConfigurationProperties in BlobStorageProperties.
Introduced BlobStorageClientConfig to provide BlobServiceClient and BlobContainerClient beans via properties.
InvoiceStorageClient now receives clients and properties through constructor.
> fix: updated download api
